### ISSUE TITLE
Parameter swapping

### ISSUE THREAD

**Issue by aburgsta** [sixpearls/simupy#1]
Hello sixpearls,

I tried to follow your talk from the scipy converence and tried to build the parameter swap you showed based on the viscous damping of the pendulum. The problem, I can see in the debugger, that the parameters will be set and so on I can see that the parameters are delivered to the viscous module, but the simulation itself always run with the value which was initial set.
I added you my code plus the pdf output of the figure.
Thank you merry much, lg aburgsta

[Viscous_Damping.pdf](https://github.com/sixpearls/simupy/files/3372289/Viscous_Damping.pdf)

**Comment by sixpearls** [comment]
Hi @aburgsta, it looks like you are using an old version of the project. I recommend you install from source from the latest development version from https://github.com/simupy/simupy. If this does not resolve the problems, please open an issue on that repository.
